// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestNetworkMapping
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Initializes and performs a scan of a network if IP address if valid
        /// </summary>
        public void ScanNetwork()
        {
            #region Variable Declarations
            WpfButton uIScanButton = this.UINetworkMappingWindow.UIScanButton;
            #endregion

            // Click 'Scan' button
            Mouse.Click(uIScanButton, new Point(22, 9));
        }
        
        #region Properties
        public UINetworkMappingWindow UINetworkMappingWindow
        {
            get
            {
                if ((this.mUINetworkMappingWindow == null))
                {
                    this.mUINetworkMappingWindow = new UINetworkMappingWindow();
                }
                return this.mUINetworkMappingWindow;
            }
        }
        #endregion
        
        #region Fields
        private UINetworkMappingWindow mUINetworkMappingWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UINetworkMappingWindow : WpfWindow
    {
        
        public UINetworkMappingWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Network Mapping";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Network Mapping");
            #endregion
        }
        
        #region Properties
        public WpfButton UIScanButton
        {
            get
            {
                if ((this.mUIScanButton == null))
                {
                    this.mUIScanButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIScanButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "ScanButton";
                    this.mUIScanButton.WindowTitles.Add("Network Mapping");
                    #endregion
                }
                return this.mUIScanButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIScanButton;
        #endregion
    }
}
